services:
  mariadb:
    container_name: web-mariadb-13
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 13-WebCalculatorDb
    ports:
      - "5113:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web-app-calculator-13
    build: .
    ports:
      - "5013:5013"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge