pipeline {
 agent any
  stages {
   stage('Hello') {
    steps {
     echo 'Hello jenkins'
    }
   }
   stage('Build Docker Image') {
    steps {
     bat 'ls -l'
     bat 'docker compose build'
    }
   }
   stage('Start Docker Container') {
    steps {
     bat 'docker compose up -d'
    }
   }
  }
}