pipeline {
    agent any
    
    stages {
        stage('Hello') {
            steps {
                echo 'Hello jenkins'
            }
        }
		
        stage('Build Docker Image') {
            steps {
                script {
                    if (isUnix()) {
						dir('App_practical/Calculator'){
							sh 'ls -l'
							sh 'docker compose build'
						}
                    } else {
						dir('App_practical/Calculator')
							bat 'dir'
							bat 'docker compose build'
						}
                    }
                }
            }
        }
        
        stage('Start Docker Container') {
            steps {
                script {
                    if (isUnix()) {
						dir('App_practical/Calculator'){
							sh 'docker compose up -d'
						}
                    } else {
						dir('App_practical/Calculator'){
							bat 'docker compose up -d'
						}
                    }
                }
            }
        }
    }
}